// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockUpdate.proto

package packet;

public final class BlockUpdateOuterClass {
  private BlockUpdateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packet.BlockUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    int getPacketId();

    /**
     * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
     * @return The position.
     */
    packet.BlockUpdateOuterClass.BlockUpdate.Vector3 getPosition();
    /**
     * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
     */
    packet.BlockUpdateOuterClass.BlockUpdate.Vector3OrBuilder getPositionOrBuilder();

    /**
     * <code>int32 block = 3;</code>
     * @return The block.
     */
    int getBlock();

    /**
     * <code>int32 blockData = 4;</code>
     * @return The blockData.
     */
    int getBlockData();
  }
  /**
   * Protobuf type {@code packet.BlockUpdate}
   */
  public static final class BlockUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packet.BlockUpdate)
      BlockUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockUpdate.newBuilder() to construct.
    private BlockUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockUpdate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BlockUpdate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              packetId_ = input.readInt32();
              break;
            }
            case 18: {
              packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(packet.BlockUpdateOuterClass.BlockUpdate.Vector3.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              block_ = input.readInt32();
              break;
            }
            case 32: {

              blockData_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.BlockUpdateOuterClass.BlockUpdate.class, packet.BlockUpdateOuterClass.BlockUpdate.Builder.class);
    }

    public interface Vector3OrBuilder extends
        // @@protoc_insertion_point(interface_extends:packet.BlockUpdate.Vector3)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 x = 1;</code>
       * @return The x.
       */
      int getX();

      /**
       * <code>int32 y = 2;</code>
       * @return The y.
       */
      int getY();

      /**
       * <code>int32 z = 3;</code>
       * @return The z.
       */
      int getZ();
    }
    /**
     * Protobuf type {@code packet.BlockUpdate.Vector3}
     */
    public static final class Vector3 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:packet.BlockUpdate.Vector3)
        Vector3OrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Vector3.newBuilder() to construct.
      private Vector3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Vector3() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Vector3();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Vector3(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                x_ = input.readInt32();
                break;
              }
              case 16: {

                y_ = input.readInt32();
                break;
              }
              case 24: {

                z_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_Vector3_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_Vector3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.BlockUpdateOuterClass.BlockUpdate.Vector3.class, packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder.class);
      }

      public static final int X_FIELD_NUMBER = 1;
      private int x_;
      /**
       * <code>int32 x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 2;
      private int y_;
      /**
       * <code>int32 y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }

      public static final int Z_FIELD_NUMBER = 3;
      private int z_;
      /**
       * <code>int32 z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public int getZ() {
        return z_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (x_ != 0) {
          output.writeInt32(1, x_);
        }
        if (y_ != 0) {
          output.writeInt32(2, y_);
        }
        if (z_ != 0) {
          output.writeInt32(3, z_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (x_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, x_);
        }
        if (y_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, y_);
        }
        if (z_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, z_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof packet.BlockUpdateOuterClass.BlockUpdate.Vector3)) {
          return super.equals(obj);
        }
        packet.BlockUpdateOuterClass.BlockUpdate.Vector3 other = (packet.BlockUpdateOuterClass.BlockUpdate.Vector3) obj;

        if (getX()
            != other.getX()) return false;
        if (getY()
            != other.getY()) return false;
        if (getZ()
            != other.getZ()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getX();
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + getY();
        hash = (37 * hash) + Z_FIELD_NUMBER;
        hash = (53 * hash) + getZ();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(packet.BlockUpdateOuterClass.BlockUpdate.Vector3 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code packet.BlockUpdate.Vector3}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:packet.BlockUpdate.Vector3)
          packet.BlockUpdateOuterClass.BlockUpdate.Vector3OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_Vector3_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_Vector3_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  packet.BlockUpdateOuterClass.BlockUpdate.Vector3.class, packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder.class);
        }

        // Construct using packet.BlockUpdateOuterClass.BlockUpdate.Vector3.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          x_ = 0;

          y_ = 0;

          z_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_Vector3_descriptor;
        }

        @java.lang.Override
        public packet.BlockUpdateOuterClass.BlockUpdate.Vector3 getDefaultInstanceForType() {
          return packet.BlockUpdateOuterClass.BlockUpdate.Vector3.getDefaultInstance();
        }

        @java.lang.Override
        public packet.BlockUpdateOuterClass.BlockUpdate.Vector3 build() {
          packet.BlockUpdateOuterClass.BlockUpdate.Vector3 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public packet.BlockUpdateOuterClass.BlockUpdate.Vector3 buildPartial() {
          packet.BlockUpdateOuterClass.BlockUpdate.Vector3 result = new packet.BlockUpdateOuterClass.BlockUpdate.Vector3(this);
          result.x_ = x_;
          result.y_ = y_;
          result.z_ = z_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof packet.BlockUpdateOuterClass.BlockUpdate.Vector3) {
            return mergeFrom((packet.BlockUpdateOuterClass.BlockUpdate.Vector3)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(packet.BlockUpdateOuterClass.BlockUpdate.Vector3 other) {
          if (other == packet.BlockUpdateOuterClass.BlockUpdate.Vector3.getDefaultInstance()) return this;
          if (other.getX() != 0) {
            setX(other.getX());
          }
          if (other.getY() != 0) {
            setY(other.getY());
          }
          if (other.getZ() != 0) {
            setZ(other.getZ());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          packet.BlockUpdateOuterClass.BlockUpdate.Vector3 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (packet.BlockUpdateOuterClass.BlockUpdate.Vector3) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int x_ ;
        /**
         * <code>int32 x = 1;</code>
         * @return The x.
         */
        @java.lang.Override
        public int getX() {
          return x_;
        }
        /**
         * <code>int32 x = 1;</code>
         * @param value The x to set.
         * @return This builder for chaining.
         */
        public Builder setX(int value) {
          
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 x = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearX() {
          
          x_ = 0;
          onChanged();
          return this;
        }

        private int y_ ;
        /**
         * <code>int32 y = 2;</code>
         * @return The y.
         */
        @java.lang.Override
        public int getY() {
          return y_;
        }
        /**
         * <code>int32 y = 2;</code>
         * @param value The y to set.
         * @return This builder for chaining.
         */
        public Builder setY(int value) {
          
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 y = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearY() {
          
          y_ = 0;
          onChanged();
          return this;
        }

        private int z_ ;
        /**
         * <code>int32 z = 3;</code>
         * @return The z.
         */
        @java.lang.Override
        public int getZ() {
          return z_;
        }
        /**
         * <code>int32 z = 3;</code>
         * @param value The z to set.
         * @return This builder for chaining.
         */
        public Builder setZ(int value) {
          
          z_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 z = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearZ() {
          
          z_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:packet.BlockUpdate.Vector3)
      }

      // @@protoc_insertion_point(class_scope:packet.BlockUpdate.Vector3)
      private static final packet.BlockUpdateOuterClass.BlockUpdate.Vector3 DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new packet.BlockUpdateOuterClass.BlockUpdate.Vector3();
      }

      public static packet.BlockUpdateOuterClass.BlockUpdate.Vector3 getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Vector3>
          PARSER = new com.google.protobuf.AbstractParser<Vector3>() {
        @java.lang.Override
        public Vector3 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Vector3(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Vector3> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Vector3> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public packet.BlockUpdateOuterClass.BlockUpdate.Vector3 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PACKETID_FIELD_NUMBER = 1;
    private int packetId_;
    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    @java.lang.Override
    public int getPacketId() {
      return packetId_;
    }

    public static final int POSITION_FIELD_NUMBER = 2;
    private packet.BlockUpdateOuterClass.BlockUpdate.Vector3 position_;
    /**
     * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
     * @return Whether the position field is set.
     */
    @java.lang.Override
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
     * @return The position.
     */
    @java.lang.Override
    public packet.BlockUpdateOuterClass.BlockUpdate.Vector3 getPosition() {
      return position_ == null ? packet.BlockUpdateOuterClass.BlockUpdate.Vector3.getDefaultInstance() : position_;
    }
    /**
     * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
     */
    @java.lang.Override
    public packet.BlockUpdateOuterClass.BlockUpdate.Vector3OrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int BLOCK_FIELD_NUMBER = 3;
    private int block_;
    /**
     * <code>int32 block = 3;</code>
     * @return The block.
     */
    @java.lang.Override
    public int getBlock() {
      return block_;
    }

    public static final int BLOCKDATA_FIELD_NUMBER = 4;
    private int blockData_;
    /**
     * <code>int32 blockData = 4;</code>
     * @return The blockData.
     */
    @java.lang.Override
    public int getBlockData() {
      return blockData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetId_ != 0) {
        output.writeInt32(1, packetId_);
      }
      if (position_ != null) {
        output.writeMessage(2, getPosition());
      }
      if (block_ != 0) {
        output.writeInt32(3, block_);
      }
      if (blockData_ != 0) {
        output.writeInt32(4, blockData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, packetId_);
      }
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPosition());
      }
      if (block_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, block_);
      }
      if (blockData_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, blockData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof packet.BlockUpdateOuterClass.BlockUpdate)) {
        return super.equals(obj);
      }
      packet.BlockUpdateOuterClass.BlockUpdate other = (packet.BlockUpdateOuterClass.BlockUpdate) obj;

      if (getPacketId()
          != other.getPacketId()) return false;
      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (getBlock()
          != other.getBlock()) return false;
      if (getBlockData()
          != other.getBlockData()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKETID_FIELD_NUMBER;
      hash = (53 * hash) + getPacketId();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (37 * hash) + BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getBlock();
      hash = (37 * hash) + BLOCKDATA_FIELD_NUMBER;
      hash = (53 * hash) + getBlockData();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.BlockUpdateOuterClass.BlockUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(packet.BlockUpdateOuterClass.BlockUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.BlockUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packet.BlockUpdate)
        packet.BlockUpdateOuterClass.BlockUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.BlockUpdateOuterClass.BlockUpdate.class, packet.BlockUpdateOuterClass.BlockUpdate.Builder.class);
      }

      // Construct using packet.BlockUpdateOuterClass.BlockUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packetId_ = 0;

        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        block_ = 0;

        blockData_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.BlockUpdateOuterClass.internal_static_packet_BlockUpdate_descriptor;
      }

      @java.lang.Override
      public packet.BlockUpdateOuterClass.BlockUpdate getDefaultInstanceForType() {
        return packet.BlockUpdateOuterClass.BlockUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public packet.BlockUpdateOuterClass.BlockUpdate build() {
        packet.BlockUpdateOuterClass.BlockUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public packet.BlockUpdateOuterClass.BlockUpdate buildPartial() {
        packet.BlockUpdateOuterClass.BlockUpdate result = new packet.BlockUpdateOuterClass.BlockUpdate(this);
        result.packetId_ = packetId_;
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.block_ = block_;
        result.blockData_ = blockData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.BlockUpdateOuterClass.BlockUpdate) {
          return mergeFrom((packet.BlockUpdateOuterClass.BlockUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.BlockUpdateOuterClass.BlockUpdate other) {
        if (other == packet.BlockUpdateOuterClass.BlockUpdate.getDefaultInstance()) return this;
        if (other.getPacketId() != 0) {
          setPacketId(other.getPacketId());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.getBlock() != 0) {
          setBlock(other.getBlock());
        }
        if (other.getBlockData() != 0) {
          setBlockData(other.getBlockData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.BlockUpdateOuterClass.BlockUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.BlockUpdateOuterClass.BlockUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int packetId_ ;
      /**
       * <code>int32 packetId = 1;</code>
       * @return The packetId.
       */
      @java.lang.Override
      public int getPacketId() {
        return packetId_;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @param value The packetId to set.
       * @return This builder for chaining.
       */
      public Builder setPacketId(int value) {
        
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketId() {
        
        packetId_ = 0;
        onChanged();
        return this;
      }

      private packet.BlockUpdateOuterClass.BlockUpdate.Vector3 position_;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.BlockUpdateOuterClass.BlockUpdate.Vector3, packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder, packet.BlockUpdateOuterClass.BlockUpdate.Vector3OrBuilder> positionBuilder_;
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       * @return The position.
       */
      public packet.BlockUpdateOuterClass.BlockUpdate.Vector3 getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? packet.BlockUpdateOuterClass.BlockUpdate.Vector3.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       */
      public Builder setPosition(packet.BlockUpdateOuterClass.BlockUpdate.Vector3 value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       */
      public Builder setPosition(
          packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       */
      public Builder mergePosition(packet.BlockUpdateOuterClass.BlockUpdate.Vector3 value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              packet.BlockUpdateOuterClass.BlockUpdate.Vector3.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       */
      public packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder getPositionBuilder() {
        
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       */
      public packet.BlockUpdateOuterClass.BlockUpdate.Vector3OrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              packet.BlockUpdateOuterClass.BlockUpdate.Vector3.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.packet.BlockUpdate.Vector3 position = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.BlockUpdateOuterClass.BlockUpdate.Vector3, packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder, packet.BlockUpdateOuterClass.BlockUpdate.Vector3OrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.BlockUpdateOuterClass.BlockUpdate.Vector3, packet.BlockUpdateOuterClass.BlockUpdate.Vector3.Builder, packet.BlockUpdateOuterClass.BlockUpdate.Vector3OrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private int block_ ;
      /**
       * <code>int32 block = 3;</code>
       * @return The block.
       */
      @java.lang.Override
      public int getBlock() {
        return block_;
      }
      /**
       * <code>int32 block = 3;</code>
       * @param value The block to set.
       * @return This builder for chaining.
       */
      public Builder setBlock(int value) {
        
        block_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 block = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlock() {
        
        block_ = 0;
        onChanged();
        return this;
      }

      private int blockData_ ;
      /**
       * <code>int32 blockData = 4;</code>
       * @return The blockData.
       */
      @java.lang.Override
      public int getBlockData() {
        return blockData_;
      }
      /**
       * <code>int32 blockData = 4;</code>
       * @param value The blockData to set.
       * @return This builder for chaining.
       */
      public Builder setBlockData(int value) {
        
        blockData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 blockData = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockData() {
        
        blockData_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packet.BlockUpdate)
    }

    // @@protoc_insertion_point(class_scope:packet.BlockUpdate)
    private static final packet.BlockUpdateOuterClass.BlockUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new packet.BlockUpdateOuterClass.BlockUpdate();
    }

    public static packet.BlockUpdateOuterClass.BlockUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockUpdate>
        PARSER = new com.google.protobuf.AbstractParser<BlockUpdate>() {
      @java.lang.Override
      public BlockUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public packet.BlockUpdateOuterClass.BlockUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_BlockUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_BlockUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_BlockUpdate_Vector3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_BlockUpdate_Vector3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BlockUpdate.proto\022\006packet\"\234\001\n\013BlockUpd" +
      "ate\022\020\n\010packetId\030\001 \001(\005\022-\n\010position\030\002 \001(\0132" +
      "\033.packet.BlockUpdate.Vector3\022\r\n\005block\030\003 " +
      "\001(\005\022\021\n\tblockData\030\004 \001(\005\032*\n\007Vector3\022\t\n\001x\030\001" +
      " \001(\005\022\t\n\001y\030\002 \001(\005\022\t\n\001z\030\003 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_packet_BlockUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packet_BlockUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_BlockUpdate_descriptor,
        new java.lang.String[] { "PacketId", "Position", "Block", "BlockData", });
    internal_static_packet_BlockUpdate_Vector3_descriptor =
      internal_static_packet_BlockUpdate_descriptor.getNestedTypes().get(0);
    internal_static_packet_BlockUpdate_Vector3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_BlockUpdate_Vector3_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
