// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Input.proto

package packet;

public final class InputOuterClass {
  private InputOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packet.Input)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 packetId = 1;</code>
     * @return Whether the packetId field is set.
     */
    boolean hasPacketId();
    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    int getPacketId();

    /**
     * <code>int32 playerId = 2;</code>
     * @return Whether the playerId field is set.
     */
    boolean hasPlayerId();
    /**
     * <code>int32 playerId = 2;</code>
     * @return The playerId.
     */
    int getPlayerId();

    /**
     * <code>int32 inputType = 3;</code>
     * @return Whether the inputType field is set.
     */
    boolean hasInputType();
    /**
     * <code>int32 inputType = 3;</code>
     * @return The inputType.
     */
    int getInputType();

    /**
     * <code>int32 inputAction = 4;</code>
     * @return Whether the inputAction field is set.
     */
    boolean hasInputAction();
    /**
     * <code>int32 inputAction = 4;</code>
     * @return The inputAction.
     */
    int getInputAction();
  }
  /**
   * Protobuf type {@code packet.Input}
   */
  public static final class Input extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packet.Input)
      InputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Input.newBuilder() to construct.
    private Input(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Input() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Input();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Input(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              packetId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              inputType_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              inputAction_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.InputOuterClass.internal_static_packet_Input_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.InputOuterClass.internal_static_packet_Input_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.InputOuterClass.Input.class, packet.InputOuterClass.Input.Builder.class);
    }

    private int bitField0_;
    public static final int PACKETID_FIELD_NUMBER = 1;
    private int packetId_;
    /**
     * <code>int32 packetId = 1;</code>
     * @return Whether the packetId field is set.
     */
    @java.lang.Override
    public boolean hasPacketId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    @java.lang.Override
    public int getPacketId() {
      return packetId_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerId_;
    /**
     * <code>int32 playerId = 2;</code>
     * @return Whether the playerId field is set.
     */
    @java.lang.Override
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>int32 playerId = 2;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public int getPlayerId() {
      return playerId_;
    }

    public static final int INPUTTYPE_FIELD_NUMBER = 3;
    private int inputType_;
    /**
     * <code>int32 inputType = 3;</code>
     * @return Whether the inputType field is set.
     */
    @java.lang.Override
    public boolean hasInputType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>int32 inputType = 3;</code>
     * @return The inputType.
     */
    @java.lang.Override
    public int getInputType() {
      return inputType_;
    }

    public static final int INPUTACTION_FIELD_NUMBER = 4;
    private int inputAction_;
    /**
     * <code>int32 inputAction = 4;</code>
     * @return Whether the inputAction field is set.
     */
    @java.lang.Override
    public boolean hasInputAction() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>int32 inputAction = 4;</code>
     * @return The inputAction.
     */
    @java.lang.Override
    public int getInputAction() {
      return inputAction_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, packetId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, inputType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, inputAction_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, packetId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, inputType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, inputAction_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof packet.InputOuterClass.Input)) {
        return super.equals(obj);
      }
      packet.InputOuterClass.Input other = (packet.InputOuterClass.Input) obj;

      if (hasPacketId() != other.hasPacketId()) return false;
      if (hasPacketId()) {
        if (getPacketId()
            != other.getPacketId()) return false;
      }
      if (hasPlayerId() != other.hasPlayerId()) return false;
      if (hasPlayerId()) {
        if (getPlayerId()
            != other.getPlayerId()) return false;
      }
      if (hasInputType() != other.hasInputType()) return false;
      if (hasInputType()) {
        if (getInputType()
            != other.getInputType()) return false;
      }
      if (hasInputAction() != other.hasInputAction()) return false;
      if (hasInputAction()) {
        if (getInputAction()
            != other.getInputAction()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPacketId()) {
        hash = (37 * hash) + PACKETID_FIELD_NUMBER;
        hash = (53 * hash) + getPacketId();
      }
      if (hasPlayerId()) {
        hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerId();
      }
      if (hasInputType()) {
        hash = (37 * hash) + INPUTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getInputType();
      }
      if (hasInputAction()) {
        hash = (37 * hash) + INPUTACTION_FIELD_NUMBER;
        hash = (53 * hash) + getInputAction();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static packet.InputOuterClass.Input parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.InputOuterClass.Input parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.InputOuterClass.Input parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.InputOuterClass.Input parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.InputOuterClass.Input parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.InputOuterClass.Input parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.InputOuterClass.Input parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.InputOuterClass.Input parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.InputOuterClass.Input parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static packet.InputOuterClass.Input parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.InputOuterClass.Input parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.InputOuterClass.Input parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(packet.InputOuterClass.Input prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.Input}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packet.Input)
        packet.InputOuterClass.InputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.InputOuterClass.internal_static_packet_Input_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.InputOuterClass.internal_static_packet_Input_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.InputOuterClass.Input.class, packet.InputOuterClass.Input.Builder.class);
      }

      // Construct using packet.InputOuterClass.Input.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packetId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        inputType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        inputAction_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.InputOuterClass.internal_static_packet_Input_descriptor;
      }

      @java.lang.Override
      public packet.InputOuterClass.Input getDefaultInstanceForType() {
        return packet.InputOuterClass.Input.getDefaultInstance();
      }

      @java.lang.Override
      public packet.InputOuterClass.Input build() {
        packet.InputOuterClass.Input result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public packet.InputOuterClass.Input buildPartial() {
        packet.InputOuterClass.Input result = new packet.InputOuterClass.Input(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packetId_ = packetId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.playerId_ = playerId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.inputType_ = inputType_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.inputAction_ = inputAction_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.InputOuterClass.Input) {
          return mergeFrom((packet.InputOuterClass.Input)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.InputOuterClass.Input other) {
        if (other == packet.InputOuterClass.Input.getDefaultInstance()) return this;
        if (other.hasPacketId()) {
          setPacketId(other.getPacketId());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasInputType()) {
          setInputType(other.getInputType());
        }
        if (other.hasInputAction()) {
          setInputAction(other.getInputAction());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.InputOuterClass.Input parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.InputOuterClass.Input) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int packetId_ ;
      /**
       * <code>int32 packetId = 1;</code>
       * @return Whether the packetId field is set.
       */
      @java.lang.Override
      public boolean hasPacketId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @return The packetId.
       */
      @java.lang.Override
      public int getPacketId() {
        return packetId_;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @param value The packetId to set.
       * @return This builder for chaining.
       */
      public Builder setPacketId(int value) {
        bitField0_ |= 0x00000001;
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetId_ = 0;
        onChanged();
        return this;
      }

      private int playerId_ ;
      /**
       * <code>int32 playerId = 2;</code>
       * @return Whether the playerId field is set.
       */
      @java.lang.Override
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private int inputType_ ;
      /**
       * <code>int32 inputType = 3;</code>
       * @return Whether the inputType field is set.
       */
      @java.lang.Override
      public boolean hasInputType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>int32 inputType = 3;</code>
       * @return The inputType.
       */
      @java.lang.Override
      public int getInputType() {
        return inputType_;
      }
      /**
       * <code>int32 inputType = 3;</code>
       * @param value The inputType to set.
       * @return This builder for chaining.
       */
      public Builder setInputType(int value) {
        bitField0_ |= 0x00000004;
        inputType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 inputType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInputType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        inputType_ = 0;
        onChanged();
        return this;
      }

      private int inputAction_ ;
      /**
       * <code>int32 inputAction = 4;</code>
       * @return Whether the inputAction field is set.
       */
      @java.lang.Override
      public boolean hasInputAction() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>int32 inputAction = 4;</code>
       * @return The inputAction.
       */
      @java.lang.Override
      public int getInputAction() {
        return inputAction_;
      }
      /**
       * <code>int32 inputAction = 4;</code>
       * @param value The inputAction to set.
       * @return This builder for chaining.
       */
      public Builder setInputAction(int value) {
        bitField0_ |= 0x00000008;
        inputAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 inputAction = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearInputAction() {
        bitField0_ = (bitField0_ & ~0x00000008);
        inputAction_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packet.Input)
    }

    // @@protoc_insertion_point(class_scope:packet.Input)
    private static final packet.InputOuterClass.Input DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new packet.InputOuterClass.Input();
    }

    public static packet.InputOuterClass.Input getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Input>
        PARSER = new com.google.protobuf.AbstractParser<Input>() {
      @java.lang.Override
      public Input parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Input(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Input> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Input> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public packet.InputOuterClass.Input getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_Input_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_Input_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Input.proto\022\006packet\"\237\001\n\005Input\022\025\n\010packe" +
      "tId\030\001 \001(\005H\000\210\001\001\022\025\n\010playerId\030\002 \001(\005H\001\210\001\001\022\026\n" +
      "\tinputType\030\003 \001(\005H\002\210\001\001\022\030\n\013inputAction\030\004 \001" +
      "(\005H\003\210\001\001B\013\n\t_packetIdB\013\n\t_playerIdB\014\n\n_in" +
      "putTypeB\016\n\014_inputActionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_packet_Input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packet_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_Input_descriptor,
        new java.lang.String[] { "PacketId", "PlayerId", "InputType", "InputAction", "PacketId", "PlayerId", "InputType", "InputAction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
