// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerJoin.proto

package packet;

public final class PlayerJoinOuterClass {
  private PlayerJoinOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerJoinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packet.PlayerJoin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 packetId = 1;</code>
     * @return Whether the packetId field is set.
     */
    boolean hasPacketId();
    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    int getPacketId();

    /**
     * <code>int32 playerId = 2;</code>
     * @return Whether the playerId field is set.
     */
    boolean hasPlayerId();
    /**
     * <code>int32 playerId = 2;</code>
     * @return The playerId.
     */
    int getPlayerId();

    /**
     * <code>string message = 3;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
     * @return The position.
     */
    packet.PlayerJoinOuterClass.PlayerJoin.Vector3f getPosition();
    /**
     * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
     */
    packet.PlayerJoinOuterClass.PlayerJoin.Vector3fOrBuilder getPositionOrBuilder();
  }
  /**
   * Protobuf type {@code packet.PlayerJoin}
   */
  public static final class PlayerJoin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packet.PlayerJoin)
      PlayerJoinOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerJoin.newBuilder() to construct.
    private PlayerJoin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerJoin() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerJoin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerJoin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              packetId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              message_ = s;
              break;
            }
            case 34: {
              packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.PlayerJoinOuterClass.PlayerJoin.class, packet.PlayerJoinOuterClass.PlayerJoin.Builder.class);
    }

    public interface Vector3fOrBuilder extends
        // @@protoc_insertion_point(interface_extends:packet.PlayerJoin.Vector3f)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      float getX();

      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      float getY();

      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      float getZ();
    }
    /**
     * Protobuf type {@code packet.PlayerJoin.Vector3f}
     */
    public static final class Vector3f extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:packet.PlayerJoin.Vector3f)
        Vector3fOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Vector3f.newBuilder() to construct.
      private Vector3f(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Vector3f() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Vector3f();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Vector3f(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {

                x_ = input.readFloat();
                break;
              }
              case 21: {

                y_ = input.readFloat();
                break;
              }
              case 29: {

                z_ = input.readFloat();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_Vector3f_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_Vector3f_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.class, packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder.class);
      }

      public static final int X_FIELD_NUMBER = 1;
      private float x_;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 2;
      private float y_;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }

      public static final int Z_FIELD_NUMBER = 3;
      private float z_;
      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public float getZ() {
        return z_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (x_ != 0F) {
          output.writeFloat(1, x_);
        }
        if (y_ != 0F) {
          output.writeFloat(2, y_);
        }
        if (z_ != 0F) {
          output.writeFloat(3, z_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (x_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(1, x_);
        }
        if (y_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, y_);
        }
        if (z_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, z_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof packet.PlayerJoinOuterClass.PlayerJoin.Vector3f)) {
          return super.equals(obj);
        }
        packet.PlayerJoinOuterClass.PlayerJoin.Vector3f other = (packet.PlayerJoinOuterClass.PlayerJoin.Vector3f) obj;

        if (java.lang.Float.floatToIntBits(getX())
            != java.lang.Float.floatToIntBits(
                other.getX())) return false;
        if (java.lang.Float.floatToIntBits(getY())
            != java.lang.Float.floatToIntBits(
                other.getY())) return false;
        if (java.lang.Float.floatToIntBits(getZ())
            != java.lang.Float.floatToIntBits(
                other.getZ())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getX());
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getY());
        hash = (37 * hash) + Z_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getZ());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(packet.PlayerJoinOuterClass.PlayerJoin.Vector3f prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code packet.PlayerJoin.Vector3f}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:packet.PlayerJoin.Vector3f)
          packet.PlayerJoinOuterClass.PlayerJoin.Vector3fOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_Vector3f_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_Vector3f_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.class, packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder.class);
        }

        // Construct using packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          x_ = 0F;

          y_ = 0F;

          z_ = 0F;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_Vector3f_descriptor;
        }

        @java.lang.Override
        public packet.PlayerJoinOuterClass.PlayerJoin.Vector3f getDefaultInstanceForType() {
          return packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.getDefaultInstance();
        }

        @java.lang.Override
        public packet.PlayerJoinOuterClass.PlayerJoin.Vector3f build() {
          packet.PlayerJoinOuterClass.PlayerJoin.Vector3f result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public packet.PlayerJoinOuterClass.PlayerJoin.Vector3f buildPartial() {
          packet.PlayerJoinOuterClass.PlayerJoin.Vector3f result = new packet.PlayerJoinOuterClass.PlayerJoin.Vector3f(this);
          result.x_ = x_;
          result.y_ = y_;
          result.z_ = z_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof packet.PlayerJoinOuterClass.PlayerJoin.Vector3f) {
            return mergeFrom((packet.PlayerJoinOuterClass.PlayerJoin.Vector3f)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(packet.PlayerJoinOuterClass.PlayerJoin.Vector3f other) {
          if (other == packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.getDefaultInstance()) return this;
          if (other.getX() != 0F) {
            setX(other.getX());
          }
          if (other.getY() != 0F) {
            setY(other.getY());
          }
          if (other.getZ() != 0F) {
            setZ(other.getZ());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          packet.PlayerJoinOuterClass.PlayerJoin.Vector3f parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (packet.PlayerJoinOuterClass.PlayerJoin.Vector3f) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private float x_ ;
        /**
         * <code>float x = 1;</code>
         * @return The x.
         */
        @java.lang.Override
        public float getX() {
          return x_;
        }
        /**
         * <code>float x = 1;</code>
         * @param value The x to set.
         * @return This builder for chaining.
         */
        public Builder setX(float value) {
          
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float x = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearX() {
          
          x_ = 0F;
          onChanged();
          return this;
        }

        private float y_ ;
        /**
         * <code>float y = 2;</code>
         * @return The y.
         */
        @java.lang.Override
        public float getY() {
          return y_;
        }
        /**
         * <code>float y = 2;</code>
         * @param value The y to set.
         * @return This builder for chaining.
         */
        public Builder setY(float value) {
          
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float y = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearY() {
          
          y_ = 0F;
          onChanged();
          return this;
        }

        private float z_ ;
        /**
         * <code>float z = 3;</code>
         * @return The z.
         */
        @java.lang.Override
        public float getZ() {
          return z_;
        }
        /**
         * <code>float z = 3;</code>
         * @param value The z to set.
         * @return This builder for chaining.
         */
        public Builder setZ(float value) {
          
          z_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float z = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearZ() {
          
          z_ = 0F;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:packet.PlayerJoin.Vector3f)
      }

      // @@protoc_insertion_point(class_scope:packet.PlayerJoin.Vector3f)
      private static final packet.PlayerJoinOuterClass.PlayerJoin.Vector3f DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new packet.PlayerJoinOuterClass.PlayerJoin.Vector3f();
      }

      public static packet.PlayerJoinOuterClass.PlayerJoin.Vector3f getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Vector3f>
          PARSER = new com.google.protobuf.AbstractParser<Vector3f>() {
        @java.lang.Override
        public Vector3f parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Vector3f(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Vector3f> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Vector3f> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public packet.PlayerJoinOuterClass.PlayerJoin.Vector3f getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PACKETID_FIELD_NUMBER = 1;
    private int packetId_;
    /**
     * <code>int32 packetId = 1;</code>
     * @return Whether the packetId field is set.
     */
    @java.lang.Override
    public boolean hasPacketId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    @java.lang.Override
    public int getPacketId() {
      return packetId_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerId_;
    /**
     * <code>int32 playerId = 2;</code>
     * @return Whether the playerId field is set.
     */
    @java.lang.Override
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>int32 playerId = 2;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public int getPlayerId() {
      return playerId_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 3;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 4;
    private packet.PlayerJoinOuterClass.PlayerJoin.Vector3f position_;
    /**
     * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
     * @return Whether the position field is set.
     */
    @java.lang.Override
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
     * @return The position.
     */
    @java.lang.Override
    public packet.PlayerJoinOuterClass.PlayerJoin.Vector3f getPosition() {
      return position_ == null ? packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.getDefaultInstance() : position_;
    }
    /**
     * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
     */
    @java.lang.Override
    public packet.PlayerJoinOuterClass.PlayerJoin.Vector3fOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, packetId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (position_ != null) {
        output.writeMessage(4, getPosition());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, packetId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPosition());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof packet.PlayerJoinOuterClass.PlayerJoin)) {
        return super.equals(obj);
      }
      packet.PlayerJoinOuterClass.PlayerJoin other = (packet.PlayerJoinOuterClass.PlayerJoin) obj;

      if (hasPacketId() != other.hasPacketId()) return false;
      if (hasPacketId()) {
        if (getPacketId()
            != other.getPacketId()) return false;
      }
      if (hasPlayerId() != other.hasPlayerId()) return false;
      if (hasPlayerId()) {
        if (getPlayerId()
            != other.getPlayerId()) return false;
      }
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPacketId()) {
        hash = (37 * hash) + PACKETID_FIELD_NUMBER;
        hash = (53 * hash) + getPacketId();
      }
      if (hasPlayerId()) {
        hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerId();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.PlayerJoinOuterClass.PlayerJoin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(packet.PlayerJoinOuterClass.PlayerJoin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.PlayerJoin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packet.PlayerJoin)
        packet.PlayerJoinOuterClass.PlayerJoinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.PlayerJoinOuterClass.PlayerJoin.class, packet.PlayerJoinOuterClass.PlayerJoin.Builder.class);
      }

      // Construct using packet.PlayerJoinOuterClass.PlayerJoin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packetId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.PlayerJoinOuterClass.internal_static_packet_PlayerJoin_descriptor;
      }

      @java.lang.Override
      public packet.PlayerJoinOuterClass.PlayerJoin getDefaultInstanceForType() {
        return packet.PlayerJoinOuterClass.PlayerJoin.getDefaultInstance();
      }

      @java.lang.Override
      public packet.PlayerJoinOuterClass.PlayerJoin build() {
        packet.PlayerJoinOuterClass.PlayerJoin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public packet.PlayerJoinOuterClass.PlayerJoin buildPartial() {
        packet.PlayerJoinOuterClass.PlayerJoin result = new packet.PlayerJoinOuterClass.PlayerJoin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packetId_ = packetId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.playerId_ = playerId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.PlayerJoinOuterClass.PlayerJoin) {
          return mergeFrom((packet.PlayerJoinOuterClass.PlayerJoin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.PlayerJoinOuterClass.PlayerJoin other) {
        if (other == packet.PlayerJoinOuterClass.PlayerJoin.getDefaultInstance()) return this;
        if (other.hasPacketId()) {
          setPacketId(other.getPacketId());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000004;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.PlayerJoinOuterClass.PlayerJoin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.PlayerJoinOuterClass.PlayerJoin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int packetId_ ;
      /**
       * <code>int32 packetId = 1;</code>
       * @return Whether the packetId field is set.
       */
      @java.lang.Override
      public boolean hasPacketId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @return The packetId.
       */
      @java.lang.Override
      public int getPacketId() {
        return packetId_;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @param value The packetId to set.
       * @return This builder for chaining.
       */
      public Builder setPacketId(int value) {
        bitField0_ |= 0x00000001;
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetId_ = 0;
        onChanged();
        return this;
      }

      private int playerId_ ;
      /**
       * <code>int32 playerId = 2;</code>
       * @return Whether the playerId field is set.
       */
      @java.lang.Override
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 3;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }

      private packet.PlayerJoinOuterClass.PlayerJoin.Vector3f position_;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerJoinOuterClass.PlayerJoin.Vector3f, packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder, packet.PlayerJoinOuterClass.PlayerJoin.Vector3fOrBuilder> positionBuilder_;
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       * @return The position.
       */
      public packet.PlayerJoinOuterClass.PlayerJoin.Vector3f getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       */
      public Builder setPosition(packet.PlayerJoinOuterClass.PlayerJoin.Vector3f value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       */
      public Builder setPosition(
          packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       */
      public Builder mergePosition(packet.PlayerJoinOuterClass.PlayerJoin.Vector3f value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       */
      public packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder getPositionBuilder() {
        
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       */
      public packet.PlayerJoinOuterClass.PlayerJoin.Vector3fOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.packet.PlayerJoin.Vector3f position = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerJoinOuterClass.PlayerJoin.Vector3f, packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder, packet.PlayerJoinOuterClass.PlayerJoin.Vector3fOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.PlayerJoinOuterClass.PlayerJoin.Vector3f, packet.PlayerJoinOuterClass.PlayerJoin.Vector3f.Builder, packet.PlayerJoinOuterClass.PlayerJoin.Vector3fOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packet.PlayerJoin)
    }

    // @@protoc_insertion_point(class_scope:packet.PlayerJoin)
    private static final packet.PlayerJoinOuterClass.PlayerJoin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new packet.PlayerJoinOuterClass.PlayerJoin();
    }

    public static packet.PlayerJoinOuterClass.PlayerJoin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerJoin>
        PARSER = new com.google.protobuf.AbstractParser<PlayerJoin>() {
      @java.lang.Override
      public PlayerJoin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerJoin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerJoin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerJoin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public packet.PlayerJoinOuterClass.PlayerJoin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_PlayerJoin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_PlayerJoin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_PlayerJoin_Vector3f_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_PlayerJoin_Vector3f_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PlayerJoin.proto\022\006packet\"\322\001\n\nPlayerJoi" +
      "n\022\025\n\010packetId\030\001 \001(\005H\000\210\001\001\022\025\n\010playerId\030\002 \001" +
      "(\005H\001\210\001\001\022\024\n\007message\030\003 \001(\tH\002\210\001\001\022-\n\010positio" +
      "n\030\004 \001(\0132\033.packet.PlayerJoin.Vector3f\032+\n\010" +
      "Vector3f\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(" +
      "\002B\013\n\t_packetIdB\013\n\t_playerIdB\n\n\010_messageb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_packet_PlayerJoin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packet_PlayerJoin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_PlayerJoin_descriptor,
        new java.lang.String[] { "PacketId", "PlayerId", "Message", "Position", "PacketId", "PlayerId", "Message", });
    internal_static_packet_PlayerJoin_Vector3f_descriptor =
      internal_static_packet_PlayerJoin_descriptor.getNestedTypes().get(0);
    internal_static_packet_PlayerJoin_Vector3f_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_PlayerJoin_Vector3f_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
