// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerUpdate.proto

package packet;

public final class PlayerUpdateOuterClass {
  private PlayerUpdateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packet.PlayerUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    int getPacketId();

    /**
     * <code>int32 playerId = 2;</code>
     * @return The playerId.
     */
    int getPlayerId();

    /**
     * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
     * @return The position.
     */
    packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getPosition();
    /**
     * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
     */
    packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getPositionOrBuilder();

    /**
     * <code>int32 health = 4;</code>
     * @return The health.
     */
    int getHealth();

    /**
     * <code>bool onGround = 5;</code>
     * @return The onGround.
     */
    boolean getOnGround();

    /**
     * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
     * @return Whether the rotation field is set.
     */
    boolean hasRotation();
    /**
     * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
     * @return The rotation.
     */
    packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getRotation();
    /**
     * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
     */
    packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getRotationOrBuilder();

    /**
     * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
     * @return Whether the headRotation field is set.
     */
    boolean hasHeadRotation();
    /**
     * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
     * @return The headRotation.
     */
    packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getHeadRotation();
    /**
     * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
     */
    packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getHeadRotationOrBuilder();
  }
  /**
   * Protobuf type {@code packet.PlayerUpdate}
   */
  public static final class PlayerUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packet.PlayerUpdate)
      PlayerUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerUpdate.newBuilder() to construct.
    private PlayerUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerUpdate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerUpdate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              packetId_ = input.readInt32();
              break;
            }
            case 16: {

              playerId_ = input.readInt32();
              break;
            }
            case 26: {
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              health_ = input.readInt32();
              break;
            }
            case 40: {

              onGround_ = input.readBool();
              break;
            }
            case 50: {
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder subBuilder = null;
              if (rotation_ != null) {
                subBuilder = rotation_.toBuilder();
              }
              rotation_ = input.readMessage(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rotation_);
                rotation_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder subBuilder = null;
              if (headRotation_ != null) {
                subBuilder = headRotation_.toBuilder();
              }
              headRotation_ = input.readMessage(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(headRotation_);
                headRotation_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.PlayerUpdateOuterClass.PlayerUpdate.class, packet.PlayerUpdateOuterClass.PlayerUpdate.Builder.class);
    }

    public interface Vector3fOrBuilder extends
        // @@protoc_insertion_point(interface_extends:packet.PlayerUpdate.Vector3f)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      float getX();

      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      float getY();

      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      float getZ();
    }
    /**
     * Protobuf type {@code packet.PlayerUpdate.Vector3f}
     */
    public static final class Vector3f extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:packet.PlayerUpdate.Vector3f)
        Vector3fOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Vector3f.newBuilder() to construct.
      private Vector3f(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Vector3f() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Vector3f();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Vector3f(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {

                x_ = input.readFloat();
                break;
              }
              case 21: {

                y_ = input.readFloat();
                break;
              }
              case 29: {

                z_ = input.readFloat();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_Vector3f_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_Vector3f_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.class, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder.class);
      }

      public static final int X_FIELD_NUMBER = 1;
      private float x_;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 2;
      private float y_;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }

      public static final int Z_FIELD_NUMBER = 3;
      private float z_;
      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public float getZ() {
        return z_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (x_ != 0F) {
          output.writeFloat(1, x_);
        }
        if (y_ != 0F) {
          output.writeFloat(2, y_);
        }
        if (z_ != 0F) {
          output.writeFloat(3, z_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (x_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(1, x_);
        }
        if (y_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, y_);
        }
        if (z_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, z_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f)) {
          return super.equals(obj);
        }
        packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f other = (packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f) obj;

        if (java.lang.Float.floatToIntBits(getX())
            != java.lang.Float.floatToIntBits(
                other.getX())) return false;
        if (java.lang.Float.floatToIntBits(getY())
            != java.lang.Float.floatToIntBits(
                other.getY())) return false;
        if (java.lang.Float.floatToIntBits(getZ())
            != java.lang.Float.floatToIntBits(
                other.getZ())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getX());
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getY());
        hash = (37 * hash) + Z_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getZ());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code packet.PlayerUpdate.Vector3f}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:packet.PlayerUpdate.Vector3f)
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_Vector3f_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_Vector3f_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.class, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder.class);
        }

        // Construct using packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          x_ = 0F;

          y_ = 0F;

          z_ = 0F;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_Vector3f_descriptor;
        }

        @java.lang.Override
        public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getDefaultInstanceForType() {
          return packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance();
        }

        @java.lang.Override
        public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f build() {
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f buildPartial() {
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f result = new packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f(this);
          result.x_ = x_;
          result.y_ = y_;
          result.z_ = z_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f) {
            return mergeFrom((packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f other) {
          if (other == packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance()) return this;
          if (other.getX() != 0F) {
            setX(other.getX());
          }
          if (other.getY() != 0F) {
            setY(other.getY());
          }
          if (other.getZ() != 0F) {
            setZ(other.getZ());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private float x_ ;
        /**
         * <code>float x = 1;</code>
         * @return The x.
         */
        @java.lang.Override
        public float getX() {
          return x_;
        }
        /**
         * <code>float x = 1;</code>
         * @param value The x to set.
         * @return This builder for chaining.
         */
        public Builder setX(float value) {
          
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float x = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearX() {
          
          x_ = 0F;
          onChanged();
          return this;
        }

        private float y_ ;
        /**
         * <code>float y = 2;</code>
         * @return The y.
         */
        @java.lang.Override
        public float getY() {
          return y_;
        }
        /**
         * <code>float y = 2;</code>
         * @param value The y to set.
         * @return This builder for chaining.
         */
        public Builder setY(float value) {
          
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float y = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearY() {
          
          y_ = 0F;
          onChanged();
          return this;
        }

        private float z_ ;
        /**
         * <code>float z = 3;</code>
         * @return The z.
         */
        @java.lang.Override
        public float getZ() {
          return z_;
        }
        /**
         * <code>float z = 3;</code>
         * @param value The z to set.
         * @return This builder for chaining.
         */
        public Builder setZ(float value) {
          
          z_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float z = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearZ() {
          
          z_ = 0F;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:packet.PlayerUpdate.Vector3f)
      }

      // @@protoc_insertion_point(class_scope:packet.PlayerUpdate.Vector3f)
      private static final packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f();
      }

      public static packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Vector3f>
          PARSER = new com.google.protobuf.AbstractParser<Vector3f>() {
        @java.lang.Override
        public Vector3f parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Vector3f(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Vector3f> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Vector3f> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PACKETID_FIELD_NUMBER = 1;
    private int packetId_;
    /**
     * <code>int32 packetId = 1;</code>
     * @return The packetId.
     */
    @java.lang.Override
    public int getPacketId() {
      return packetId_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerId_;
    /**
     * <code>int32 playerId = 2;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public int getPlayerId() {
      return playerId_;
    }

    public static final int POSITION_FIELD_NUMBER = 3;
    private packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f position_;
    /**
     * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
     * @return Whether the position field is set.
     */
    @java.lang.Override
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
     * @return The position.
     */
    @java.lang.Override
    public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getPosition() {
      return position_ == null ? packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : position_;
    }
    /**
     * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
     */
    @java.lang.Override
    public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int HEALTH_FIELD_NUMBER = 4;
    private int health_;
    /**
     * <code>int32 health = 4;</code>
     * @return The health.
     */
    @java.lang.Override
    public int getHealth() {
      return health_;
    }

    public static final int ONGROUND_FIELD_NUMBER = 5;
    private boolean onGround_;
    /**
     * <code>bool onGround = 5;</code>
     * @return The onGround.
     */
    @java.lang.Override
    public boolean getOnGround() {
      return onGround_;
    }

    public static final int ROTATION_FIELD_NUMBER = 6;
    private packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f rotation_;
    /**
     * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
     * @return Whether the rotation field is set.
     */
    @java.lang.Override
    public boolean hasRotation() {
      return rotation_ != null;
    }
    /**
     * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
     * @return The rotation.
     */
    @java.lang.Override
    public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getRotation() {
      return rotation_ == null ? packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : rotation_;
    }
    /**
     * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
     */
    @java.lang.Override
    public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getRotationOrBuilder() {
      return getRotation();
    }

    public static final int HEADROTATION_FIELD_NUMBER = 7;
    private packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f headRotation_;
    /**
     * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
     * @return Whether the headRotation field is set.
     */
    @java.lang.Override
    public boolean hasHeadRotation() {
      return headRotation_ != null;
    }
    /**
     * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
     * @return The headRotation.
     */
    @java.lang.Override
    public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getHeadRotation() {
      return headRotation_ == null ? packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : headRotation_;
    }
    /**
     * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
     */
    @java.lang.Override
    public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getHeadRotationOrBuilder() {
      return getHeadRotation();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetId_ != 0) {
        output.writeInt32(1, packetId_);
      }
      if (playerId_ != 0) {
        output.writeInt32(2, playerId_);
      }
      if (position_ != null) {
        output.writeMessage(3, getPosition());
      }
      if (health_ != 0) {
        output.writeInt32(4, health_);
      }
      if (onGround_ != false) {
        output.writeBool(5, onGround_);
      }
      if (rotation_ != null) {
        output.writeMessage(6, getRotation());
      }
      if (headRotation_ != null) {
        output.writeMessage(7, getHeadRotation());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, packetId_);
      }
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPosition());
      }
      if (health_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, health_);
      }
      if (onGround_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, onGround_);
      }
      if (rotation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getRotation());
      }
      if (headRotation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getHeadRotation());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof packet.PlayerUpdateOuterClass.PlayerUpdate)) {
        return super.equals(obj);
      }
      packet.PlayerUpdateOuterClass.PlayerUpdate other = (packet.PlayerUpdateOuterClass.PlayerUpdate) obj;

      if (getPacketId()
          != other.getPacketId()) return false;
      if (getPlayerId()
          != other.getPlayerId()) return false;
      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (getHealth()
          != other.getHealth()) return false;
      if (getOnGround()
          != other.getOnGround()) return false;
      if (hasRotation() != other.hasRotation()) return false;
      if (hasRotation()) {
        if (!getRotation()
            .equals(other.getRotation())) return false;
      }
      if (hasHeadRotation() != other.hasHeadRotation()) return false;
      if (hasHeadRotation()) {
        if (!getHeadRotation()
            .equals(other.getHeadRotation())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKETID_FIELD_NUMBER;
      hash = (53 * hash) + getPacketId();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (37 * hash) + HEALTH_FIELD_NUMBER;
      hash = (53 * hash) + getHealth();
      hash = (37 * hash) + ONGROUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOnGround());
      if (hasRotation()) {
        hash = (37 * hash) + ROTATION_FIELD_NUMBER;
        hash = (53 * hash) + getRotation().hashCode();
      }
      if (hasHeadRotation()) {
        hash = (37 * hash) + HEADROTATION_FIELD_NUMBER;
        hash = (53 * hash) + getHeadRotation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet.PlayerUpdateOuterClass.PlayerUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(packet.PlayerUpdateOuterClass.PlayerUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.PlayerUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packet.PlayerUpdate)
        packet.PlayerUpdateOuterClass.PlayerUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.PlayerUpdateOuterClass.PlayerUpdate.class, packet.PlayerUpdateOuterClass.PlayerUpdate.Builder.class);
      }

      // Construct using packet.PlayerUpdateOuterClass.PlayerUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packetId_ = 0;

        playerId_ = 0;

        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        health_ = 0;

        onGround_ = false;

        if (rotationBuilder_ == null) {
          rotation_ = null;
        } else {
          rotation_ = null;
          rotationBuilder_ = null;
        }
        if (headRotationBuilder_ == null) {
          headRotation_ = null;
        } else {
          headRotation_ = null;
          headRotationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.PlayerUpdateOuterClass.internal_static_packet_PlayerUpdate_descriptor;
      }

      @java.lang.Override
      public packet.PlayerUpdateOuterClass.PlayerUpdate getDefaultInstanceForType() {
        return packet.PlayerUpdateOuterClass.PlayerUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public packet.PlayerUpdateOuterClass.PlayerUpdate build() {
        packet.PlayerUpdateOuterClass.PlayerUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public packet.PlayerUpdateOuterClass.PlayerUpdate buildPartial() {
        packet.PlayerUpdateOuterClass.PlayerUpdate result = new packet.PlayerUpdateOuterClass.PlayerUpdate(this);
        result.packetId_ = packetId_;
        result.playerId_ = playerId_;
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.health_ = health_;
        result.onGround_ = onGround_;
        if (rotationBuilder_ == null) {
          result.rotation_ = rotation_;
        } else {
          result.rotation_ = rotationBuilder_.build();
        }
        if (headRotationBuilder_ == null) {
          result.headRotation_ = headRotation_;
        } else {
          result.headRotation_ = headRotationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.PlayerUpdateOuterClass.PlayerUpdate) {
          return mergeFrom((packet.PlayerUpdateOuterClass.PlayerUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.PlayerUpdateOuterClass.PlayerUpdate other) {
        if (other == packet.PlayerUpdateOuterClass.PlayerUpdate.getDefaultInstance()) return this;
        if (other.getPacketId() != 0) {
          setPacketId(other.getPacketId());
        }
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.getHealth() != 0) {
          setHealth(other.getHealth());
        }
        if (other.getOnGround() != false) {
          setOnGround(other.getOnGround());
        }
        if (other.hasRotation()) {
          mergeRotation(other.getRotation());
        }
        if (other.hasHeadRotation()) {
          mergeHeadRotation(other.getHeadRotation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.PlayerUpdateOuterClass.PlayerUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.PlayerUpdateOuterClass.PlayerUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int packetId_ ;
      /**
       * <code>int32 packetId = 1;</code>
       * @return The packetId.
       */
      @java.lang.Override
      public int getPacketId() {
        return packetId_;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @param value The packetId to set.
       * @return This builder for chaining.
       */
      public Builder setPacketId(int value) {
        
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packetId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketId() {
        
        packetId_ = 0;
        onChanged();
        return this;
      }

      private int playerId_ ;
      /**
       * <code>int32 playerId = 2;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(int value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0;
        onChanged();
        return this;
      }

      private packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f position_;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder> positionBuilder_;
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       * @return The position.
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       */
      public Builder setPosition(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       */
      public Builder setPosition(
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       */
      public Builder mergePosition(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder getPositionBuilder() {
        
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f position = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private int health_ ;
      /**
       * <code>int32 health = 4;</code>
       * @return The health.
       */
      @java.lang.Override
      public int getHealth() {
        return health_;
      }
      /**
       * <code>int32 health = 4;</code>
       * @param value The health to set.
       * @return This builder for chaining.
       */
      public Builder setHealth(int value) {
        
        health_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 health = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHealth() {
        
        health_ = 0;
        onChanged();
        return this;
      }

      private boolean onGround_ ;
      /**
       * <code>bool onGround = 5;</code>
       * @return The onGround.
       */
      @java.lang.Override
      public boolean getOnGround() {
        return onGround_;
      }
      /**
       * <code>bool onGround = 5;</code>
       * @param value The onGround to set.
       * @return This builder for chaining.
       */
      public Builder setOnGround(boolean value) {
        
        onGround_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool onGround = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnGround() {
        
        onGround_ = false;
        onChanged();
        return this;
      }

      private packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f rotation_;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder> rotationBuilder_;
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       * @return Whether the rotation field is set.
       */
      public boolean hasRotation() {
        return rotationBuilder_ != null || rotation_ != null;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       * @return The rotation.
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getRotation() {
        if (rotationBuilder_ == null) {
          return rotation_ == null ? packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : rotation_;
        } else {
          return rotationBuilder_.getMessage();
        }
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       */
      public Builder setRotation(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f value) {
        if (rotationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rotation_ = value;
          onChanged();
        } else {
          rotationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       */
      public Builder setRotation(
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder builderForValue) {
        if (rotationBuilder_ == null) {
          rotation_ = builderForValue.build();
          onChanged();
        } else {
          rotationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       */
      public Builder mergeRotation(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f value) {
        if (rotationBuilder_ == null) {
          if (rotation_ != null) {
            rotation_ =
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.newBuilder(rotation_).mergeFrom(value).buildPartial();
          } else {
            rotation_ = value;
          }
          onChanged();
        } else {
          rotationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       */
      public Builder clearRotation() {
        if (rotationBuilder_ == null) {
          rotation_ = null;
          onChanged();
        } else {
          rotation_ = null;
          rotationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder getRotationBuilder() {
        
        onChanged();
        return getRotationFieldBuilder().getBuilder();
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getRotationOrBuilder() {
        if (rotationBuilder_ != null) {
          return rotationBuilder_.getMessageOrBuilder();
        } else {
          return rotation_ == null ?
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : rotation_;
        }
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f rotation = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder> 
          getRotationFieldBuilder() {
        if (rotationBuilder_ == null) {
          rotationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder>(
                  getRotation(),
                  getParentForChildren(),
                  isClean());
          rotation_ = null;
        }
        return rotationBuilder_;
      }

      private packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f headRotation_;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder> headRotationBuilder_;
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       * @return Whether the headRotation field is set.
       */
      public boolean hasHeadRotation() {
        return headRotationBuilder_ != null || headRotation_ != null;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       * @return The headRotation.
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f getHeadRotation() {
        if (headRotationBuilder_ == null) {
          return headRotation_ == null ? packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : headRotation_;
        } else {
          return headRotationBuilder_.getMessage();
        }
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       */
      public Builder setHeadRotation(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f value) {
        if (headRotationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          headRotation_ = value;
          onChanged();
        } else {
          headRotationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       */
      public Builder setHeadRotation(
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder builderForValue) {
        if (headRotationBuilder_ == null) {
          headRotation_ = builderForValue.build();
          onChanged();
        } else {
          headRotationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       */
      public Builder mergeHeadRotation(packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f value) {
        if (headRotationBuilder_ == null) {
          if (headRotation_ != null) {
            headRotation_ =
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.newBuilder(headRotation_).mergeFrom(value).buildPartial();
          } else {
            headRotation_ = value;
          }
          onChanged();
        } else {
          headRotationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       */
      public Builder clearHeadRotation() {
        if (headRotationBuilder_ == null) {
          headRotation_ = null;
          onChanged();
        } else {
          headRotation_ = null;
          headRotationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder getHeadRotationBuilder() {
        
        onChanged();
        return getHeadRotationFieldBuilder().getBuilder();
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       */
      public packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder getHeadRotationOrBuilder() {
        if (headRotationBuilder_ != null) {
          return headRotationBuilder_.getMessageOrBuilder();
        } else {
          return headRotation_ == null ?
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.getDefaultInstance() : headRotation_;
        }
      }
      /**
       * <code>.packet.PlayerUpdate.Vector3f headRotation = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder> 
          getHeadRotationFieldBuilder() {
        if (headRotationBuilder_ == null) {
          headRotationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3f.Builder, packet.PlayerUpdateOuterClass.PlayerUpdate.Vector3fOrBuilder>(
                  getHeadRotation(),
                  getParentForChildren(),
                  isClean());
          headRotation_ = null;
        }
        return headRotationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packet.PlayerUpdate)
    }

    // @@protoc_insertion_point(class_scope:packet.PlayerUpdate)
    private static final packet.PlayerUpdateOuterClass.PlayerUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new packet.PlayerUpdateOuterClass.PlayerUpdate();
    }

    public static packet.PlayerUpdateOuterClass.PlayerUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerUpdate>
        PARSER = new com.google.protobuf.AbstractParser<PlayerUpdate>() {
      @java.lang.Override
      public PlayerUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public packet.PlayerUpdateOuterClass.PlayerUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_PlayerUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_PlayerUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_PlayerUpdate_Vector3f_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_PlayerUpdate_Vector3f_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PlayerUpdate.proto\022\006packet\"\230\002\n\014PlayerU" +
      "pdate\022\020\n\010packetId\030\001 \001(\005\022\020\n\010playerId\030\002 \001(" +
      "\005\022/\n\010position\030\003 \001(\0132\035.packet.PlayerUpdat" +
      "e.Vector3f\022\016\n\006health\030\004 \001(\005\022\020\n\010onGround\030\005" +
      " \001(\010\022/\n\010rotation\030\006 \001(\0132\035.packet.PlayerUp" +
      "date.Vector3f\0223\n\014headRotation\030\007 \001(\0132\035.pa" +
      "cket.PlayerUpdate.Vector3f\032+\n\010Vector3f\022\t" +
      "\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_packet_PlayerUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packet_PlayerUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_PlayerUpdate_descriptor,
        new java.lang.String[] { "PacketId", "PlayerId", "Position", "Health", "OnGround", "Rotation", "HeadRotation", });
    internal_static_packet_PlayerUpdate_Vector3f_descriptor =
      internal_static_packet_PlayerUpdate_descriptor.getNestedTypes().get(0);
    internal_static_packet_PlayerUpdate_Vector3f_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_PlayerUpdate_Vector3f_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
